### ISSUE TITLE
Please create the first github release

### ISSUE THREAD

**Issue by favoyang** [baba-s/UniSceneViewCameraAligner#2]
Hi @baba-s, 

Thanks for updating the license. Would you please make a [github releases](https://github.com/baba-s/uni-scene-view-camera-aligner/releases) v1.0.0. So openupm can automatically build package bundle based on git tags. 

preview: https://beta.openupm.com/packages/com.johnsoncodehk.unity-asset-inspector/
example with git tags (see the version history section): https://beta.openupm.com/packages/com.littlebigfun.addressable-importer/

**Comment by baba-s** [comment]
https://github.com/baba-s/uni-scene-view-camera-aligner/releases/tag/v1.0.0

@favoyang  Is this alright with you?

**Comment by favoyang** [comment]
Looks great!

https://beta.openupm.com/packages/com.baba_s.uni-scene-view-camera-aligner/
